[package]
name = "awabi_nif"
version = "0.1.0"
authors = ["Hajime Nakagami <nakagami@gmail.com>"]
edition = "2018"

[lib]
name = "awabi_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
awabi = "0.2"
lazy_static = "1.4"
